# Generated by Django 4.1.5 on 2023-01-23 08:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('roll_no', models.IntegerField()),
                ('age', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
